services:
  - type: web
    name: flask-image-processing
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
    - key: ENV
      value: production
    healthCheckPath: /
